### ISSUE TITLE
Accionar con un clic

### ISSUE THREAD

**Issue by canonicus** [Satyam/reactc2#1]
En los elementos que tienen dos posiciones, como ser los cambios y las señales, podría existir la opción de cambiarlos de posición con sólo un clic, y que aparezca el menú con las opciones si se hace un clic largo.

**Comment by Satyam** [comment]
Aparentemente, según nuestras conversaciones previas, el único elemento que necesita más de un click para cambiar, sería el `Triple`.  Dado que las señales que controlan el acceso estarían en rojo, se podría ciclar entre las tres posibles posiciones haciendo sucesivos clicks.

**Comment by Satyam** [comment]
Falta accionar las señales con un simple click.
