### ISSUE TITLE
Tabla de enclavamiento

### ISSUE THREAD

**Issue by canonicus** [Satyam/reactc2#2]
Una de las opciones al hacer clic largo en un elemento podría ser que muestre la tabla de enclavamiento, es decir, la lista de elementos que habría que mover para poder mover el elemento seleccionado. Podría mostrar con distinto color los que no están en la posición correcta.

**Comment by Satyam** [comment]
Al irme a acostar ayer se me encendió la lamparita.  Estábamos hablando de dos cosas distintas, una de las cuales tengo hecha, la otra que no sabía cómo integrar, hasta que ayer me di cuenta que siendo cosas distintas, no se pueden integrar.
Las acciones que uno ejecuta tienen consecuencias, un bloque ocupado tiene como consecuencia ciertas señales que se ponen en rojo, y el ponerse en rojo puede hacer que las señales anteriores se pongan en amarillo.  
Pero las acciones pueden tener requisitos, cosas que deben ocurrir antes de que se puedan ejecutar: un cambio requiere que las señales que lo enmarcan estén en rojo y/o que el bloque en que se encuentra no esté ocupado.
Lo que vos me venís pidiendo es lo segundo y lo  que yo tengo hecho es lo primero y, resulta que al ser cosas distintas, no entendía cómo manejarlas.  Por ejemplo, en este caso, 
Para empezar, lo que yo tengo hecho, son 'enclavamientos'? Cómo llamarlos si no?  Quizás todos sean 'enclavamientos', unos 'pre-requisitos' y los otros 'consecuencias', quizás sean 'automatismos' y 'enclavamientos'. 
A mi me viene bien aclarar conceptos y llamar a las cosas correctamente.
